In [1]:
#dependices
import csv
import pandas as pd
import os

In [2]:
#set path for file
full_table = "Resources/population_by_country_2020.csv"

In [3]:
#read csv
file = pd.read_csv(full_table, encoding="utf-8")
file.head()

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,China,1438207241,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,India,1377233523,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,United States,330610570,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,Indonesia,272931713,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,Pakistan,219992900,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %

In [4]:
#drop and missing data
clean_table = file.dropna(how="any")

In [5]:
new_index = clean_table.set_index("Country (or dependency)")
new_index.head()

,Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
Country (or dependency),,,,,,,,,,
China,1438207241,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1377233523,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,330610570,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,272931713,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,219992900,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %

In [8]:
#Drop unneeded columns (Land Area, Migrants, Fert. Rate, Med. Age, Urban Pop %, World Share)
new_table = new_index.drop(['Yearly Change','Net Change','Land Area (Km²)','Migrants (net)', 'Fert. Rate', 'Med. Age', 'Urban Pop %', 'World Share'], axis=1)
new_table

                         Population (2020)  Density (P/Km²)
Country (or dependency)
China                           1438207241              153
India                           1377233523              464
United States                    330610570               36
Indonesia                        272931713              151
Pakistan                         219992900              287
...                                    ...              ...
Aruba                               106675              593
Tonga                               105449              147
U.S. Virgin Islands                 104456              298
Seychelles                           98224              214
Antigua and Barbuda                  97764              223

[201 rows x 2 columns]

In [ ]:
# The columns that were taken off are deemed as not useful. 
# If there is a use for them the orginal dataset can be used to join the tables

In [9]:
# write new csv
new_table.to_csv("Resources/Population_clean.csv", index=False, header=True)